version: '3.7'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8080"
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_USER: app
      POSTGRES_DB: cinema_auth
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

volumes:
  postgres_data:
