version: '3.7'

services:
  db:
    image: postgres:13
    container_name: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_USER: app
      POSTGRES_DB: movies_database
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:alpine
    container_name: auth_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: